SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[FindText]
(
@text	AS VARCHAR(50)
)
AS

SELECT ROUTINE_NAME, ROUTINE_DEFINITION 
    FROM INFORMATION_SCHEMA.ROUTINES 
    WHERE ROUTINE_DEFINITION LIKE @text 
    AND ROUTINE_TYPE='PROCEDURE'
    
SELECT TABLES.TABLE_NAME, ''
    FROM INFORMATION_SCHEMA.TABLES 
    WHERE TABLE_NAME LIKE @text 

SELECT COLUMNS.COLUMN_NAME, columns.TABLE_NAME 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE COLUMN_NAME LIKE @text 

SELECT CHECK_CONSTRAINTS.CONSTRAINT_NAME, CHECK_CONSTRAINTS.CHECK_CLAUSE 
FROM INFORMATION_SCHEMA.CHECK_CONSTRAINTS 
WHERE CHECK_CLAUSE LIKE @text 

SELECT VIEWS.TABLE_NAME, VIEWS.VIEW_DEFINITION 
FROM INFORMATION_SCHEMA.VIEWS 
WHERE VIEW_DEFINITION LIKE @text 

 
GO
